### PR TITLE
Adding the pattern and weight networks for E2E NNVtx

### PR DESCRIPTION
**Pull request by BenjaminRS**
As part of https://github.com/cms-l1t-offline/cmssw/pull/1191 we need to move the model files into the suitable cms-data areas. These are the pattern and weight networks.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
